/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'VipinK' at '12/5/16 1:01 PM' with Gradle 2.14.1
 *
 * @author VipinK, @date 12/5/16 1:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
